## This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    # To build on multiple OS un-comment below command ,and comment-out above command line-15
    # runs-on: ${{matrix.os}}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest,windows-latest,macOS-latest] #Github action only supports these three OS
       
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
#github.com/marketplace?-actions  
    - name: Build and Push Docker Image  #New step is added to build and push
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: nanajanashia/demo-app  #username/image
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }} #create secrerts using Git ghub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}
         
